server:
  port: 8080

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/springbootschool?serverTimezone=GMT%2B8
      username: root
      password: 999999

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.homework.pojo

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true




